myproject/MisPalabras/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('help', views.help_info, name='help'),
    path('mypage', views.my_page, name='my_page'),
    path('<str:name>', views.get_word, name='get_word'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('MisPalabras.urls')),
]

myproject/MisPalabras/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Word(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    definition = models.TextField(blank=True)
    image = models.TextField()
    votes = models.IntegerField(default=0)
    short_def = models.CharField(max_length=300, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    full_url = models.URLField(blank=True)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    text = models.TextField(blank=True)
    date = models.DateTimeField(auto_now=True)


class Url(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    link = models.URLField()
    date = models.DateTimeField(auto_now=True)
    description = models.TextField(blank=True)
    image = models.TextField()


class DRAEInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    word = models.OneToOneField(Word, on_delete=models.CASCADE, primary_key=True)
    description = models.TextField()
    date = models.DateTimeField(auto_now=True)


class FlickrImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    image = models.TextField(blank=True)
    date = models.DateTimeField(auto_now=True)


class ApiMeme(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    image = models.TextField(blank=True)
    text = models.TextField(blank=True)
    date = models.DateTimeField(auto_now=True)


class VoteWord(models.Model):
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    
    
    

myproject/MisPalabras/forms.py
from django import forms
from .models import Word, Comment, Url, ApiMeme
from django.contrib.auth.models import User


class WordSearchForm(forms.ModelForm):
    class Meta:
        model = Word
        fields = {'name'}

    name = forms.CharField(label='', required=False)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {'text'}

    text = forms.CharField(widget=forms.Textarea(attrs={"rows":9, "cols":15}), label='', required=False)


class UrlForm(forms.ModelForm):
    class Meta:
        model = Url
        fields = {'link'}

    link = forms.CharField(widget=forms.Textarea(attrs={"rows":9, "cols":15}), label='', required=False)


class MemeForm(forms.ModelForm):
    MEME_CHOICE = [
        ('Angry-Baby', 'Angry Baby'),
        ('Baby-Godfather', 'Baby Godfather'),
        ('Beard-Baby', 'Beard Baby'),
        ('Angry-Toddler', 'Angry Toddler')
    ]

    class Meta:
        model = ApiMeme
        fields = {'text', 'image'}

    text = forms.CharField(widget=forms.Textarea(attrs={"rows":9, "cols":15}), label='Introduzca un texto:', required=False)
    image = forms.CharField(label='Seleccione una imagen:', widget=forms.Select(choices=MEME_CHOICE), required=False)


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

myproject/MisPalabras/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import WordSearchForm, CommentForm, UrlForm, MemeForm, LoginForm
from .models import Word, Comment, DRAEInfo, Url, FlickrImage, VoteWord, ApiMeme
from bs4 import BeautifulSoup
import urllib.request
import urllib.parse
import json
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
import random
from django.views.decorators.csrf import csrf_exempt
from urllib.parse import quote
from .parser import WikiChannel
from django.core.serializers import serialize
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def login_or_signup(request, action):
    created = True
    exists = False

    data = request.POST
    username = data.get("username")
    password = data.get("password")

    if action == "Login":
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
        else:
            created = False

    elif action == "SignUp":
        created = True
        user = authenticate(request, username=username, password=password)
        if user is None:
            user = User.objects.create_user(username=username, password=password)
            user.save()
            login(request, user)
        else:
            exists = True

    return created, exists


def wiki_info(request, name):
    url = f'https://es.wikipedia.org/w/api.php?action=query&format=xml&titles={quote(name)}&prop=extracts&exintro&explaintext'
    xml_stream = urllib.request.urlopen(url)
    definition = WikiChannel(xml_stream).definition()

    url2 = f'https://es.wikipedia.org/w/api.php?action=query&titles={quote(name)}&prop=pageimages&format=json&pithumbsize=200'
    with urllib.request.urlopen(url2) as json_doc:
        json_str = json_doc.read().decode(encoding="ISO-8859-1")
        data = json.dumps(json.loads(json_str))
        try:
            image = data.split('"source"')[1].split('"width"')[0][3:][:-3]
        except:
            image = ""

    return definition, image


def get_drae_info(request, word):
    url = f'https://dle.rae.es/{quote(word.name)}'
    user_agent = "Mozilla/5.0 (X11) Gecko/20100101 Firefox/100.0"
    req = urllib.request.Request(url, headers={'User-Agent': user_agent})
    page = urllib.request.urlopen(req)
    bs = BeautifulSoup(page.read(), 'html.parser')
    description = bs.find('meta', property='og:description')
    description = description['content']
    drae_info = DRAEInfo(user=request.user, word=word, description=description)
    drae_info.save()


def get_flickr_image(request, word):
    url = f'https://www.flickr.com/services/feeds/photos_public.gne?tags={quote(word.name)}'
    user_agent = "Mozilla/5.0 (X11) Gecko/20100101 Firefox/100.0"
    req = urllib.request.Request(url, headers={'User-Agent': user_agent})
    page = urllib.request.urlopen(req)
    bs = BeautifulSoup(page.read(), 'xml')
    image = bs.find('link', rel='enclosure')
    image = image['href']
    flickr_image = FlickrImage(user=request.user, word=word, image=image)
    flickr_image.save()


@csrf_exempt
def get_embedded_info(request):
    data = request.POST
    link = data.get("link")

    user_agent = "Mozilla/5.0 (X11) Gecko/20100101 Firefox/100.0"
    req = urllib.request.Request(link, headers={'User-Agent': user_agent})
    page = urllib.request.urlopen(req)
    bs = BeautifulSoup(page.read(), 'html.parser')

    try:
        image = bs.find('meta', property='og:image')
        image = image['content']
    except:
        image = ""

    try:
        description = bs.find('meta', property='og:description')

        if description is None:
            description = bs.find('meta', property='og:title')

        description = description['content']
    except:
        description = ""

    return image, description


def get_common_items(request):
    wordsearch_form = WordSearchForm(request.POST or None)
    try:
        random_word = random.choice(Word.objects.all())
        sorted_words = Word.objects.all().order_by('-votes')[:10]
        words_number = Word.objects.count()
    except IndexError:
        random_word = None
        sorted_words = None
        words_number = 0

    return wordsearch_form, random_word, sorted_words, words_number


def get_paginated_words(request):
    word_list = Word.objects.all().order_by('-date')

    paginator = Paginator(word_list, 5)
    page = request.GET.get('page')

    try:
        paginated_words = paginator.page(page)
    except PageNotAnInteger:  # Deliver first page
        paginated_words = paginator.page(1)
    except EmptyPage:  # Deliver last page
        paginated_words = paginator.page(paginator.num_pages)

    return paginated_words


@csrf_exempt
def index(request):
    wordsearch_form, random_word, sorted_words, words_number = get_common_items(request)
    login_form = LoginForm(request.POST or None)
    created = True
    exists = False

    if request.method == "POST":
        action = request.POST["action"]

        if action == "Login" or action == "SignUp":
            if login_form.is_valid():
                created, exists = login_or_signup(request, action)

        elif action == "Logout":
            created = True
            logout(request)

        elif action == "SearchWord":
            if wordsearch_form.is_valid():
                data = request.POST
                name = data.get("name")
                return redirect('get_word', name=name)

    paginated_words = get_paginated_words(request)

    context = {
        'created': created,
        'exists': exists,
        'login_form': login_form,
        'word_list': paginated_words,
        'wordsearch_form': wordsearch_form,
        'sorted_words': sorted_words,
        'words_number': words_number,
        'random_word': random_word,
    }

    format = request.GET.get('format')
    if format == 'xml':
        content = serialize('xml', Word.objects.all())
        return HttpResponse(content, content_type="application/xml")

    elif format == 'json':
        content = serialize('json', Word.objects.all())
        return HttpResponse(content, content_type="application/json")

    return render(request, 'MisPalabras/index.html', context)


@csrf_exempt
def get_word(request, name):
    try:
        word = Word.objects.get(name=name)
        comment_form = CommentForm(request.POST or None)
        url_form = UrlForm(request.POST or None)
        meme_form = MemeForm(request.POST or None)
        if request.user.is_authenticated:
            try:
                vote_word = VoteWord.objects.get(user=request.user, word=word)
            except VoteWord.DoesNotExist:
                vote_word = ""
        else:
            vote_word = ""
        wordsearch_form, random_word, sorted_words, words_number = get_common_items(request)
        login_form = LoginForm(request.POST or None)
        created = True
        exists = False

        if request.method == "POST":
            action = request.POST["action"]

            if action == "Login" or action == "SignUp":
                if login_form.is_valid():
                    created, exists = login_or_signup(request, action)

            elif action == "Logout":
                created = True
                logout(request)

            elif action == "SearchWord":
                if wordsearch_form.is_valid():
                    data = request.POST
                    name = data.get("name")
                    return redirect('get_word', name=name)

            elif action == "SendComment":
                if comment_form.is_valid():
                    comment_form.instance.user = request.user
                    comment_form.instance.word = word
                    comment = comment_form.save()
                    comment.save()
                return redirect('get_word', name=word.name)

            elif action == "SendUrl":
                if url_form.is_valid():
                    url_form.instance.user = request.user
                    url_form.instance.word = word
                    url = url_form.save()
                    image, description = get_embedded_info(request)
                    url.image = image
                    url.description = description
                    url.save()
                return redirect('get_word', name=word.name)

            elif action == "DRAEInfo":
                get_drae_info(request, word)
                return redirect('get_word', name=word.name)

            elif action == "FlickrImage":
                get_flickr_image(request, word)
                return redirect('get_word', name=word.name)

            elif action == "SendMeme":
                if meme_form.is_valid():
                    meme_form.instance.user = request.user
                    meme_form.instance.word = word
                    meme = meme_form.save()
                    data = request.POST
                    text = data.get("text")
                    image = data.get("image")
                    url = f'http://apimeme.com/meme?meme={quote(image)}&top={quote(word.name)}&bottom={quote(text)}'
                    meme.image = url
                    meme.text = text
                    meme.save()
                return redirect('get_word', name=word.name)

            elif action == "VoteWord":
                word.votes += 1
                word.save()
                vote_word = VoteWord(user=request.user, word=word)
                vote_word.save()
                return redirect('get_word', name=word.name)

            elif action == "DeleteVote":
                word.votes -= 1
                word.save()
                VoteWord.objects.filter(user=request.user, word=word).delete()
                return redirect('get_word', name=word.name)

        context = {
            'crated': created,
            'exists': exists,

myproject/MisPalabras/templates/MisPalabras/index.html
{% extends 'MisPalabras/schema.html' %}
{% block body %}
    <div id="wordlist" class="container-fluid">
        {% if word_list %}
            {% for word in word_list %}
                <br>
                <h5><a class="text-dark" style="text-decoration:none" href="/{{ word.name }}">{{ word.name }}</a></h5>
                {% if word.image %}
                <div class="row">
                    <div class="col-lg-10 col-sm-7">
                        <small>{{ word.short_def }}...</small>
                    </div>
                    <br>
                    <div class="col-lg-3 col-sm-6">
                        <br>
                        <img src="{{ word.image }}">
                    </div>
                </div>
                {% else %}
                    <div>
                        <small>{{ word.short_def }}...</small>
                    </div>
                {% endif %}
                <br>
                <footer><small><i>Palabra "{{ word.name }}" guardada por {{ word.user.username }}</i></small></footer>
                <footer><small><p id="votes"><i>Número de votos: {{ word.votes }} </i></p></small></footer>
        {% endfor %}

            {% if word_list.has_next or word_list.has_previous %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-end">
                    {% if word_list.has_previous %}
                        <li>
                            <strong><a style="color:black" href="?page={{ word_list.previous_page_number }}" class="page-link" tabindex="-1">Anterior</a></strong>
                            </a>
                        </li>
                    {% endif %}

                    {% for page in word_list.paginator.page_range %}
                        <li class="{% if word_list.number == page %}active{% endif %}">
                            <strong><a style="color:black" class="page-link" href="?page={{ page }}" >{{ page }}</a></strong>
                        </li>
                    {% endfor %}

                    {% if word_list.has_next %}
                        <li>
                            <strong><a style="color:black" href="?page={{ word_list.next_page_number }}" class="page-link">Siguiente</a></strong>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        {% else %}
            <br>
            <h4>No hay palabras guardadas.</h4>
            <br>
            <h4>Regístrese o inicie sesión. Después, introduzca una palabra.</h4>
        {% endif %}
    </div>
{% endblock %}

myproject/MisPalabras/templates/MisPalabras/my_page.html
{% extends 'MisPalabras/schema.html' %}
{% block body %}
    <div>
        {% if request.user.is_authenticated %}
            <form action="" method="POST">
            {% csrf_token %}
                <br>
                <h5 class="bi-person-fill">{{ request.user.username }}</h5>
                <button class="bi-trash-fill" type="submit" name="action" value="Delete">Eliminar cuenta</button>
            </form>
            <br>
        {% endif %}
    </div>


    <h3>Mi página</h3>
    <hr>

    {% if word_list %}
        <h4>Palabras guardadas</h4>
        <br>
        {% for word in word_list %}
            <h5>{{ word.name }}</h5>
            <small>{{ word.short_def }}...</small>
            <footer id="obtained"><small><i>Extraído de <strong><a class="text-dark" style="text-decoration:none" href="/{{ word.name }}">{{ word.name }}</a></strong>.</i></small></footer>
            <br>
        {% endfor %}
        <br>
    {% endif %}

    {% if drae_info_list %}
        <h4>Definiciones del Diccionario de la RAE</h4>
        {% for drae_info in drae_info_list %}
            {{ drae_info.description }}
            <footer id="obtained"><small><i>Extraído de <strong><a class="text-dark" style="text-decoration:none" href="/{{ drae_info.word.name }}">{{ drae_info.word.name }}</a></strong>.</i></small></footer>
            <br>
        {% endfor %}
        <br>
    {% endif %}

    {% if comment_list %}
        <h4>Comentarios</h4>
        {% for comment in comment_list %}
            {{ comment.text }}
            <footer id="obtained"><small><i>Extraído de <strong><a class="text-dark" style="text-decoration:none" href="/{{ comment.word.name }}">{{ comment.word.name }}</a></strong>.</i></small></footer>
            <br>
        {% endfor %}
        <br>
    {% endif %}

    {% if url_list %}
        <h4>Enlaces</h4>
        {% for url in url_list %}
            <a href="{{ url.link }}">{{ url.link }}</a>
            <footer id="obtained"><small><i>Extraído de <strong><a class="text-dark" style="text-decoration:none" href="/{{ url.word.name }}">{{ url.word.name }}</a></strong>.</i></small></footer>
            <br>
        {% endfor %}
        <br>
    {% endif %}

    {% if flickr_image_list %}
        <h4>Imágenes de Flickr</h4>
        <div class="row">
            {% for flickr_image in flickr_image_list %}
                <div class="col-lg-3 col-sm-4">
                    <img src="{{ flickr_image.image }}" width="50%">
                    <footer id="obtained"><small><i>Extraído de <strong><a class="text-dark" style="text-decoration:none" href="/{{ flickr_image.word.name }}">{{ flickr_image.word.name }}</a></strong>.</i></small></footer>
                </div>
            {% endfor %}
        </div>
        <br>
    {% endif %}

    {% if meme_list %}
        <h4>Memes</h4>
        <div class="row">
            {% for meme in meme_list %}
                <div class="col-lg-3 col-sm-4">
                    <img src="{{ meme.image }}" width="50%">
                    <footer id="obtained"><small><i>Extraído de <strong><a class="text-dark" style="text-decoration:none" href="/{{ meme.word.name }}">{{ meme.word.name }}</a></strong>.</i></small></footer>
                </div>
            {% endfor %}
        </div>
        <br>
    {% endif %}
{% endblock %}

myproject/MisPalabras/templates/MisPalabras/word_page.html
{% extends 'MisPalabras/schema.html' %}
{% load static %}

{% block body %}
    <div class="container-fluid">
        {% if word %}
            <br>
            <h5>{{ word.name }}</h5>
            <div class="navbar-nav-scroll">
                <br>
                <img id="img_wiki" src="{{ word.image }}">
                <p>{{ word.definition }}</p>
            </div>

            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-sm-12">
                        <div class="col-lg-11 col-sm-12">
                            {% if request.user.is_authenticated %}
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    <br>
                                    <h5> Acceder al Diccionario de la RAE:</h5>
                                    <button class="autoinfo" type="submit" name="action" value="DRAEInfo"><img src="{% static 'MisPalabras/logo-rae.png' %}" height="60" width="100"></button>
                                </form>
                            {% endif %}
                        </div>

                        <br>
                        {% if word.draeinfo %}
                        <h5>Definición DRAE añadida:</h5>
                            <b>{{ word.user.username }}</b>
                            <p>{{ word.draeinfo.description }}</p>
                            <footer><small><i>Información extraída de
                                <strong><a class="text-dark" style="text-decoration:none" href="https://dle.rae.es/{{ word.name }}">DRAE
                                </a></strong> {{ word.draeinfo.date }}</i></small></footer>
                        {% endif %}

                    </div>

                    <div class="col-lg-5 col-sm-10">
                        {% if request.user.is_authenticated %}
                            <form action="" method="POST">
                                {% csrf_token %}
                                <br>
                                <h5>Añadir Flickr:</h5>
                                <button class="autoinfo" type="submit" name="action" value="FlickrImage"><img src="{% static 'MisPalabras/logo-Flickr.png' %}" height="60" width="100"></button>
                            </form>
                        {% endif %}

                        <br>
                        <div class="navbar-nav-scroll">
                            <div class="row"
                                <br>
                                {% for flickr_image in word.flickrimage_set.all %}
                                    <h5>Imágenes de Flickr añadidas:</h5>
                                    <div class="col-lg-7 col-sm-5">
                                        <p><b>{{ flickr_image.user.username }}</b></p>
                                        <img id="flickr" src="{{ flickr_image.image }}" width="50%">
                                        <p><div><small><i>Imagen extraída de
                                        <strong><a class="text-dark" style="text-decoration:none" href="https://www.flickr.com/services/feeds/photos_public.gne?tags={{ word.name }}">Flickr
                                        </a></strong> {{ flickr_image.date }}</i></small></div></p>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>

                    {% if request.user.is_authenticated %}
                        <div class="col-lg-4 col-sm-12">
                            <br>
                            <div class="col-lg-17 col-sm-10">
                                <h5>Añadir comentario:</h5>
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    {{ comment_form }}
                                    <button class="send" type="submit" name="action" value="SendComment">Enviar</button>
                                </form>
                            </div>

                            <div class="navbar-nav-scroll">
                                <div class="col-lg-17 col-sm-10">
                                    <br>
                                    <h5>Comentarios añadidos:</h5>
                                    <div class="navbar-nav-scroll">
                                        {% for comment in word.comment_set.all %}
                                            <b>{{ comment.user.username }}</b>
                                            <p>{{ comment.text }}</p>
                                            <div id="date">
                                                 <small>{{ comment.date }}</small>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-sm-6">
                            <br>
                            <div class="col-lg-6 col-sm-7">
                                <h5>Añadir enlace:</h5>
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    {{ url_form }}
                                    <button class="send" type="submit" name="action" value="SendUrl">Enviar</button>
                                </form>
                            </div>


                            <div class="col-lg-12 col-sm-7">
                                <br>
                                <div class="col-lg-8 col-sm-10">
                                    <h5>Enlaces añadidos:</h5>
                                    <div class="navbar-nav-scroll">
                                        {% for url in word.url_set.all %}
                                            <b>{{ url.user.username }}</b>
                                            {% if url.image %}
                                                <div class="cat">
                                                    <img id="img_url" src="{{ url.image }}">
                                                </div>
                                            {% endif %}
                                            {% if url.description %}
                                                <p>{{ url.description }}</p>
                                            {% endif %}
                                            <p><a href="{{ url.link }}">{{ url.link }}</a></p>
                                            <div id="date">
                                                <small>{{ url.date }}</small>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-3 col-sm-5">
                            <br>
                            <h5>Añadir meme:</h5>
                            <form action="" method="POST">
                                {% csrf_token %}
                                {{ meme_form }}
                                <button class="send" type="submit" name="action" value="SendMeme">Enviar</button>
                            </form>

                           <div class="col-lg-114 col-sm-14">
                                <br>
                                <h5>Memes añadidos:</h5>
                                <div class="navbar-nav-scroll">
                                    {% for meme in word.apimeme_set.all %}
                                        <b>{{ meme.user.username }}</b>
                                        <img src="{{ meme.image }}" width="100%">
                                        <div id="date">
                                            <p><div><small><i>Meme extraído de
                                            <strong><a class="text-dark" style="text-decoration:none" href="{{ meme.image }}">Meme
                                            </a></strong> {{ meme.date }}</i></small></div></p>
                                        </div>
                                        <br>
                                    {% endfor %}
                                </div>
                           </div>
                        </div>
                    {% endif %}
                </div>
            </div>

            <p id="votes"><i>Número de votos: {{ word.votes }} </i></p>
            {% if request.user.is_authenticated %}
                {% if vote_word %}
                    <form action="" method="POST">
                        {% csrf_token %}
                        <span id="votes"><i>Palabra votada. Quitar voto:</i></span>
                        <button class="bi-hand-thumbs-down" type="submit" name="action" value="DeleteVote"></button>
                    </form>
                {% else %}
                    <form action="" method="POST">
                        {% csrf_token %}
                        <span id="votes"><i>Votar palabra:</i></span>
                        <button class="bi-hand-thumbs-up" type="submit" name="action" value="VoteWord"></button>
                    </form>
                {% endif %}
            {% endif %}

            <br>
            <footer><small><i>Palabra "{{ word.name }}" guardada el {{ word.date }} por {{ word.user.username }} </i></small></footer>
            <br>

        {% else %}
            <div class="row">

                <div class="navbar-nav-scroll">
                    <h1>{{ name }}</h1>
                    <img id="img_wiki" src="{{ image }}">
                    <p>{{ definition }}</p>
                </div>

                <form action="" method="POST">
                    <br>
                    {% csrf_token %}
                    <button class="bi-bookmark-check" type="submit" name="action" value="Save"> Guardar</button>
                    <button class="bi-bookmark-x" type="submit" name="action" value="Delete"> No guardar</button>
                </form>

            </div>
        {% endif %}
    </div>
{% endblock %}